### PR TITLE
lowercase vat property of receipt card

### PR DESCRIPTION
**Pull request by danmarshall**
See https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-connector-api-reference#receiptcard-object

### CODE REVIEW

**Comment by danmarshall** [comment]
@billba can you give this a quick review?

**Comment by billba** [comment]
Can you point me at an authoritative source that shows that lowercase is correct?

**Comment by danmarshall** [comment]
Yes, click the link above and search for **ReceiptCard object**
Also, [this page](https://docs.microsoft.com/en-us/bot-framework/rest-api/bot-framework-rest-direct-line-3-0-concepts#developer-resources) which links to the [swagger file](https://docs.botframework.com/en-us/restapi/directline3/swagger.json) <- search for "vat" in the json.

**Comment by billba** [comment]
Perfect, thanks.

**Comment by billba** [comment]
Published as version 0.9.11

**Pull request merged**
