### PR TITLE
[WIP] Adds a configurable timeout option

### PR DESCRIPTION
**Pull request by watadarkstar**
This PR lets you configure the timeout:

```javascript
var directLine = new DirectLine({
    timeout: /* put your timeout here (default is 20000 ms) */,
});
```

TODO:
- [ ] Test
- [ ] Get rid of build folder and revert gitignore

### CODE REVIEW

**Comment by billba** [comment]
What's the thinking on committing the build folder?

**Comment by watadarkstar** [comment]
Hi @billba I just needed the build folder for testing purposes to avoid publishing to npm. As I do this in our app:

`"botframework-directlinejs": "git+ssh://git@github.com:watadarkstar/BotFramework-DirectLineJS.git#feat/timeout-option",`

**Comment by billba** [comment]
That seems like a hack to avoid a full-fledged CI/CD pipeline... there's a good reason that we don't usually check in compiled code - it makes for a very noisy set of diffs.

In any case it would be more appropriate to separate these changes into their own PRs.

**Comment by watadarkstar** [comment]
Closing in favour of #110 which does not include the build folder.

@billba I don't work for Microsoft and don't have my npm auth setup on this computer.

**Pull request closed without merging**
