### PR TITLE
Change conversationId to public access modifier

### LINKED ISSUE #48: Allow users to reference conversationId property
`conversationId` property is currently set to private [here](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L290). Users cannot reconnect to an existing conversation or handle `ConnectionStatus.ExpiredToken` state.

Change the access modifier to public to allow users to store `conversationId` externally in a db/localstorage.

This can be overcome by starting the conversation ourselves on the backend and passing streamUrl, token and conversationId to Directline constructor, but as of [this code](https://github.com/Microsoft/BotFramework-DirectLineJS/blob/master/src/directLine.ts#L341), the `refreshToken` loop will not be run by directline and users have to manually handle it.

### PR DESCRIPTION
**Pull request by harshithkashyap**
Closes #48

### CODE REVIEW

**Comment by chaoteng** [comment]
Does it need to make `IBotConnection` interface change as well?

**Comment by billba** [comment]
@chaoteng  No, because `IBotConnection` has no concept of `conversationId`, nor should it.

**Comment by sevetseh28** [comment]
I would also set  the secret and token to public so that we can save it to localStorage in Chat.tsx for resuming conversation.

**Comment by cwhitten** [comment]
Closing as we've drifted quite a bit from 2017

**Pull request closed without merging**
