### PR TITLE
Ignore errorConversationEnded on end()

### PR DESCRIPTION
**Pull request by orgads**
It is expected to be thrown there.

### CODE REVIEW

**Comment by orgads** [comment]
@ckkashyap Please review this.

**Comment by cwhitten** [comment]
Hi @orgads. Thank you for the pull request. Can you provide some information in the description explaining the motivations for the change and include steps to reproduce the error you're trying to avoid? Thank you.

**Comment by orgads** [comment]
I added an example to the commit message.

```
directLine.activity$
.filter(activity => activity.type === 'message')
.subscribe(
    message => {
      console.log("received message ", message)
      directLine.end();
    }
);

/.../node_modules/botframework-directlinejs/node_modules/rxjs/Subscriber.js:246
            throw err;
            ^
Error: conversation ended
    at Object.<anonymous> (/.../node_modules/botframework-directlinejs/built/directLine.js:47:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/.../azure-bot.js:3:42)
    at Module._compile (internal/modules/cjs/loader.js:686:14)
```

**Comment by orgads** [comment]
ping?

**Comment by cwhitten** [comment]
Hi @orgads. We're evaluating the side effects of this change (and the issue you are trying to address with it) in our WebChat project [here](https://github.com/Microsoft/BotFramework-WebChat). We hope to land this soon. Thank you.

**Comment by cwhitten** [comment]
@orgads is it possible to inspect the the state of the connectionStatus observer to guard the call to `next(...)` instead of wrapping the call to `next(...)` in a try/catch?

**Comment by orgads** [comment]
What do you mean?

**Comment by orgads** [comment]
Doesn't help. You can easily try it yourself. I suppose you have a key. This is my test app:

```
global.XMLHttpRequest = require('xhr2');
global.WebSocket = require('ws');
const { DirectLine } = require('./built/directLine.js');
var directLine = new DirectLine({ secret: "<key>" });
directLine.activity$
.filter(activity => activity.type === 'message')
.subscribe(
    message => directLine.end()
);
```

**Comment by orgads** [comment]
Thank you.

**Comment by a-b-r-o-w-n** [comment]
@orgads [`0.11.0`](https://www.npmjs.com/package/botframework-directlinejs/v/0.11.0) has been published to npm.

**Pull request merged**
