### PR TITLE
Avoid posting an error on intentional end

### PR DESCRIPTION
**Pull request by orgads**
Commit 544e7e328943f98d3ef2aa14404193ca08ab225f suppressed the exception,
but it is still reported as an error.

```
directLine.activity$
.filter(activity => activity.type === 'message')
.subscribe(
    message => {
      console.log("received message ", message)
      directLine.end();
    },
    err => console.error // error is logged here
);
```

### CODE REVIEW

**Comment by orgads** [comment]
Gentle ping

**Comment by orgads** [comment]
ping?

**Comment by orgads** [comment]
Hello?

**Comment by cwhitten** [comment]
hi @orgads. thank you for your patience. we'll look to include this change with our next release. someone will review along with a currently active work-stream. cc @compulim @ckkashyap

**Comment by compulim** [comment]
It's now released at 0.11.5.

https://github.com/microsoft/BotFramework-DirectLineJS/releases/tag/v0.11.5

**Pull request merged**
